/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicsBank;

import GraphicsBank.FirstDeposit;
import GraphicsBank.Start;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author rizwan
 */
public class CreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccount
     */
    
    public CreateAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        submit = new javax.swing.JLabel();
        father = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        add = new javax.swing.JTextArea();
        warn = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create An Account");
        setBounds(new java.awt.Rectangle(360, 100, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraphicsBank/cancel.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraphicsBank/CREATEpics/SUBMIT.png"))); // NOI18N
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        father.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        father.setForeground(new java.awt.Color(0, 51, 255));
        father.setToolTipText("father name");
        father.setBorder(null);
        getContentPane().add(father, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 112, 190, 30));

        mobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mobile.setForeground(new java.awt.Color(0, 51, 255));
        mobile.setToolTipText("mobile no.");
        mobile.setBorder(null);
        mobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobileKeyReleased(evt);
            }
        });
        getContentPane().add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 312, 190, 30));

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(0, 51, 255));
        name.setToolTipText("your name..");
        name.setBorder(null);
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 190, 30));

        add.setColumns(20);
        add.setForeground(new java.awt.Color(0, 51, 255));
        add.setRows(4);
        add.setTabSize(3);
        add.setToolTipText("Your address..");
        add.setBorder(null);
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 180, 90));

        warn.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        warn.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(warn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 346, 170, 10));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setFont(new java.awt.Font("Tahoma", 1, 5)); // NOI18N
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraphicsBank/CREATEpics/bg2.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
        if(name.getText().length()==0  || father.getText().length()==0 || add.getText().length()==0 || 
                mobile.getText().length()==0 )
        {
            JOptionPane.showMessageDialog(null, "Fields are Empty");
        }
        else {
             Start.N = name.getText().toUpperCase();
            Start.FN = father.getText().toUpperCase();
            Start.ADD = add.getText();
            Start.MOB = Long.parseLong(mobile.getText());
            new FirstDeposit().setVisible(true);
            this.setVisible(false);
        }
       
    }//GEN-LAST:event_submitMouseClicked

    private void mobileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileKeyReleased
        // TODO add your handling code here:
        if(mobile.getText().length() <10 || mobile.getText().length() > 10 )
        {
            warn.setText("Mobile number should be 10 Digit");
            mobile.setForeground(Color.RED);
            submit.setEnabled(false);
        }
        else{
            warn.setText("");
            mobile.setForeground(Color.BLUE);
            submit.setEnabled(true);
        }
        
        
        try {
            String s = mobile.getText();
            int i;
            for(i=0; i<s.length(); i++)
            {
                if(Character.isLetter(s.charAt(i))) {
                    JOptionPane.showMessageDialog(null, "Mobile number should be in digit");
                }
            }
                 
        } catch(Exception e) {}
    }//GEN-LAST:event_mobileKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea add;
    private javax.swing.JLabel bg;
    private javax.swing.JTextField father;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    private javax.swing.JLabel submit;
    private javax.swing.JLabel warn;
    // End of variables declaration//GEN-END:variables
}
