/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicsBank;


import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author rizwan
 */
public class Display extends javax.swing.JFrame {

    /**
     * Creates new form Display
     */
    public Display() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        account = new javax.swing.JTextField();
        balance1 = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        acn = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        submit = new javax.swing.JLabel();
        Fname = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        mob = new javax.swing.JLabel();
        forget = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Check Account Detail");
        setBounds(new java.awt.Rectangle(320, 100, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        account.setBorder(null);
        account.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                accountKeyReleased(evt);
            }
        });
        getContentPane().add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 63, 180, 29));

        balance1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        balance1.setText("Account No :");
        getContentPane().add(balance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 100, 28));

        balance.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        balance.setForeground(new java.awt.Color(0, 204, 51));
        balance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 290, 28));

        acn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        acn.setForeground(new java.awt.Color(0, 153, 204));
        acn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(acn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 310, 28));

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 310, 28));

        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraphicsBank/SUBMIT.png"))); // NOI18N
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        Fname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 310, 28));

        add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 310, 28));

        mob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 310, 28));

        forget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraphicsBank/rawImages/forget.png"))); // NOI18N
        forget.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetMouseClicked(evt);
            }
        });
        getContentPane().add(forget, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraphicsBank/rawImages/display.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 410, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
        if(account.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Please !! Enter Account Number");
        }
        else {
            
            Start.ac = Long.parseLong(account.getText());
       
        Start q =null;
        int i,j=0;
        for(i=0; i<Start.data.size(); i++)
        {
           q = Start.data.get(i);
           if(q.getAcn() == Start.ac)
           {
               j = i;
               break;
           }
          
        }
        if(i==Start.data.size())
        {
             Component msg = null;
            
            javax.swing.JOptionPane.showMessageDialog( msg, "Account Number Not Found !!!");
        }
       else {
          name.setText("Name : " + q.getName().toUpperCase());
          Fname.setText("Father's Name : " + q.getFname().toUpperCase());
          add.setText("Add :" + q.getAdd().toUpperCase());
          mob.setText("Mobile : " + q.getMob() );
          acn.setText("Account Number : " + q.getAcn());
          balance.setText("Balance : " + q.getBal() + " Rs.");
          
        }
       account.setText("");
      
        
        
        }
        
    }//GEN-LAST:event_submitMouseClicked

    private void accountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accountKeyReleased
        // TODO add your handling code here:
        try {
            String s = account.getText();
            int i;
            for(i=0; i<s.length(); i++)
            {
                if(Character.isLetter(s.charAt(i))) {
                    JOptionPane.showMessageDialog(null, "Account Number should be in digit");
                    submit.setEnabled(false);
                } else submit.setEnabled(true);
            }
                 
        } catch(Exception e) {}
    }//GEN-LAST:event_accountKeyReleased

    private void forgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetMouseClicked
        // TODO add your handling code here:
        new ForgetAccount().setVisible(true);
    }//GEN-LAST:event_forgetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fname;
    private javax.swing.JTextField account;
    private javax.swing.JLabel acn;
    private javax.swing.JLabel add;
    private javax.swing.JLabel balance;
    private javax.swing.JLabel balance1;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel forget;
    private javax.swing.JLabel mob;
    private javax.swing.JLabel name;
    private javax.swing.JLabel submit;
    // End of variables declaration//GEN-END:variables

    void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
