/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicsBank;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author rizwan
 */
public class FirstDeposit extends javax.swing.JFrame {

    /**
     * Creates new form FirstDeposit
     */
    public FirstDeposit() {
        initComponents();
        account.setText("Your Account Number is : " + Start.ACN);
        welcome.setText("Mr. " + Start.N.toUpperCase() );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        note = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        account = new javax.swing.JLabel();
        submit = new javax.swing.JLabel();
        welcome1 = new javax.swing.JLabel();
        bal = new javax.swing.JTextField();
        tick = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 100, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        note.setText("You must be Deposit minimum Rs. 500 first time.");
        getContentPane().add(note, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        welcome.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        welcome.setText("Welcome !!");
        getContentPane().add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        account.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        account.setForeground(new java.awt.Color(0, 153, 0));
        account.setText("Your Account Number is :");
        getContentPane().add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraphicsBank/SUBMIT.png"))); // NOI18N
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        welcome1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        welcome1.setText("Welcome !!");
        getContentPane().add(welcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        bal.setToolTipText("minimum 500 rs.");
        bal.setBorder(null);
        bal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                balKeyReleased(evt);
            }
        });
        getContentPane().add(bal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 170, 30));

        tick.setForeground(new java.awt.Color(0, 153, 0));
        getContentPane().add(tick, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 50, 20));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraphicsBank/rawImages/firstDeposit.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
        if(bal.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Please enter amount at least 500 Rs.");
        }
        else if(Integer.parseInt(bal.getText()) < 500 ) {
             JOptionPane.showMessageDialog(null, "First Deposit should be minimum 500 Rs.");
        }
        else {
            Start.B = Integer.parseInt(bal.getText());
            Start ob = new Start();
            Start.data.add(ob);
            ob.getData();
            JOptionPane.showMessageDialog(null, "Thank You" + "\n" + "You have succesfully created!!\n");
            this.setVisible(false);  
        }
        
    }//GEN-LAST:event_submitMouseClicked

    private void balKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_balKeyReleased
        // TODO add your handling code here:
        try{
             if(Integer.parseInt(bal.getText()) >= 500)
                {
                    tick.setText(" ✓✓✓ ");
  
                } else tick.setText("");
        }catch(Exception e) {}
       
        
        try{
            String s = bal.getText();
            int i;
            for(i=0; i<s.length(); i++)
            {
                if(Character.isLetter(s.charAt(i))) {
                    JOptionPane.showMessageDialog(null, "Amount should be in digit");
                    submit.setEnabled(false);
                }
                else submit.setEnabled(true);
            }
        }catch(Exception e) {}
    }//GEN-LAST:event_balKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstDeposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel account;
    private javax.swing.JTextField bal;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel note;
    private javax.swing.JLabel submit;
    private javax.swing.JLabel tick;
    private javax.swing.JLabel welcome;
    private javax.swing.JLabel welcome1;
    // End of variables declaration//GEN-END:variables
}
