/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicsBank;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author rizwan
 */
public class ForgetAccount extends javax.swing.JFrame {

    /**
     * Creates new form ForgetAccount
     */
    public ForgetAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submit = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        acn = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(321, 100, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraphicsBank/SUBMIT.png"))); // NOI18N
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        info.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        info.setForeground(new java.awt.Color(0, 102, 0));
        info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 320, 50));

        acn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        acn.setForeground(new java.awt.Color(0, 0, 204));
        acn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(acn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 320, 50));

        mobile.setBorder(null);
        getContentPane().add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 68, 182, 29));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraphicsBank/rawImages/forgetAcn.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
        if(mobile.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Please !! Enter Mobile Number");
        }
        else {
            
            Start.getMob = Long.parseLong(mobile.getText());
       
        Start q =null;
        int i,j=0;
        for(i=0; i<Start.data.size(); i++)
        {
           q = Start.data.get(i);
           if(q.getMob() == Start.getMob)
           {
               j = i;
               break;
           }
          
        }
        if(i==Start.data.size())
        {
             Component msg = null;
            
            javax.swing.JOptionPane.showMessageDialog( msg, "Mobile Number Not Found !!!");
        }
       else {
          //name.setText("Name : " + q.getName().toUpperCase());
          info.setText("Your Account Number");
          acn.setText(""+q.getAcn());    
        }
       mobile.setText("");
      
        
        
        }
        
    }//GEN-LAST:event_submitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acn;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel info;
    private javax.swing.JTextField mobile;
    private javax.swing.JLabel submit;
    // End of variables declaration//GEN-END:variables
}
