/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicsBank;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author rizwan
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    private String Name;
    private String F_name;
    private String Address;
    private long Mob;
    private double balance;
    private long acn;
    
    public static String N;
    public static String FN;
    public static String ADD;
    public static long MOB;
    public static double B;
    public static long ACN = 7499000;
    
    public static long ac; // For geting Account number to check
    public static long Recv_ac; // Receiver Account number
    public static long getMob;
    
    public static ArrayList <Start> data;
    public Start() {
        initComponents();
        Name = null;
        F_name = null;
        Address = null;
        Mob = 0;
        balance = 0.0;
        acn = ACN++;
        getDate();
         
    }
    Thread t;
    Runnable r = new Runnable() {
        @Override
        public void run() {
            try{
                while(true)
                {
                    Date date = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("E dd-MM-yyyy | KK:mm:ss a");
        dt.setText(ft.format(date)+"");
                }
                
            }catch(Exception e){}
        
            }
    };
    public void getDate() 
    {
      t = new Thread(r);
        t.start();
    }
    
    public void getData()
    {
        Name = N;
        F_name = FN;
        Address = ADD;
        Mob = MOB;
        balance = B;
    }
    
    public long getAcn()
    {
        return(acn);
    }
    
    public String getName()
    {
        return(Name);
    }
    
    public String getFname()
    {
        return(F_name);
    }
    
    public String getAdd()
    {
        return(Address);
    }
    
    public long getMob()
    {
        return(Mob);
    }
    
    public Double getBal()
    {
        return(balance);
    }
    
    public void Withdraw()
    {
       if(B>balance) 
       {
           JOptionPane.showMessageDialog(null, "You have insufficient balance");
       }
       else
       {
        balance = balance - B;
        Withdraw.info.setText("Transaction form " + getAcn() +  " account number");
        Withdraw.withdraw.setText("You withdraw " + B + " Rs.");
        Withdraw.balance.setText("Your Balance is " + balance + " Rs.");
        
        JOptionPane.showMessageDialog(null, "Transaction Sussecfull");
       }
           
    }
    
    public void Deposit()
    {
        balance = balance + B;
        Deposit.info.setText("Deposited in " + getAcn() +  " account number");
        Deposit.withdraw.setText("You Deposit " + B + " Rs.");
        Deposit.balance.setText("Your Balance is " + balance + " Rs.");
        
        JOptionPane.showMessageDialog(null, "You have Sussecfully deposited");
    }
    
    public void Transfer(Start send)
    {
        if(B>send.balance)
            JOptionPane.showMessageDialog(null, "You have insufficient balance");
        else
        {
            send.balance = send.balance - B;
            balance = balance + B;
            Transfer.withdraw.setText("You Transfered " + B + " Rs. to Account number : " + getAcn());
            Transfer.balance.setText("Your Current Balance is " + send.balance + " Rs.");
            JOptionPane.showMessageDialog(null, "Succesfully Transfered");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DEMO BANK");
        setBounds(new java.awt.Rectangle(260, 100, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dt.setForeground(new java.awt.Color(51, 153, 255));
        dt.setText("Time");
        getContentPane().add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraphicsBank/pics/title.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 450, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraphicsBank/pics/create.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 150, 210, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraphicsBank/pics/transfer.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraphicsBank/pics/deposit.png"))); // NOI18N
        jLabel4.setText("bb");
        jLabel4.setToolTipText("");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 190, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraphicsBank/pics/withdraw.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraphicsBank/pics/exit.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 90, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraphicsBank/pics/accountdetail.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraphicsBank/pics/backgrond.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new CreateAccount().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        new Display().setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new Withdraw().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        new Deposit().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        new Transfer().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
        
        data = new ArrayList <Start> ();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel dt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
