/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculator;


import javax.swing.JOptionPane;

/**
 *
 * @author rizwan
 */
public class SimpleCalc extends javax.swing.JFrame {

    /**
     * Creates new form SimpleCalc
     */
    double  First;
    double Sec;
    double Result;
    double min = 0;
    double res=1;
    String operator;
    public SimpleCalc() {
        initComponents();
        Display.setEditable(false);
    }
    
    public void equalTo()
    {
      try {
            Sec = Double.parseDouble(Display.getText()) ;
        }catch(Exception e) {}
        
        if(operator == "+")
        {
          Result = First + Sec;
          Display.setText(""+Result);
          
        }
        if(operator == "-")
        {
          Result = First - Sec;
          Display.setText(""+Result);
          
        }
        if(operator == "*")
        {
          Result = First * Sec;
          Display.setText(""+Result);
          
        }
        if(operator == "/")
        {
          Result = First / Sec;
          Display.setText(""+Result);
          
          
        }
    }
    
    public void Get()
    {
        First = Double.parseDouble(store.getText()) ;
        store.setText("");
       
        if(operator == "+")
        {
           Result = Result + First;
          
        }
        if(operator == "-")
        {
           min = (First - min);
           Result = (-1)*(min);
          
        }
        if(operator == "*")
        {
           res = res* First;
           Result = res;
          
        }
        if(operator == "/")
        {
          res =  First/res;
          Result = (1/res);
          
        }
    }
    
    /*public void Operator(String op)
    {
        Sec = Long.parseLong(Display.getText());
        switch(op)
        {
            case "+":  
            Result = First + Sec;
            break;
            case "-":  
            Sec = Long.parseLong(Display.getText());
            Result = First + Sec;
            break;
            case "*":  
            Sec = Long.parseLong(Display.getText());
            Result = First + Sec;
            break;
            case "/":  
            Sec = Long.parseLong(Display.getText());
            Result = First + Sec;
            break;
            default : JOptionPane.showMessageDialog(null, "hmmmm");
        }
    }*/
    
    public void backSp()
    {
        String backspace = null;
        if(Display.getText().length() > 0)
        {
          StringBuilder sb = new StringBuilder(Display.getText());
          sb.deleteCharAt(Display.getText().length() - 1);
          backspace = sb.toString();
          Display.setText(backspace);
        }
    }
    
    
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Display = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btnMul = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnEql = new javax.swing.JButton();
        bksc = new javax.swing.JButton();
        ans = new javax.swing.JLabel();
        store = new javax.swing.JTextField();
        in = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Display.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });
        Display.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DisplayKeyReleased(evt);
            }
        });
        getContentPane().add(Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 43));

        btn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 50, 50));

        btn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 50, 50));

        btn3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 50, 50));

        btn4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 50, 50));

        btn5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 50, 50));

        btn6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 50, 50));

        btn7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 50, 50));

        btn8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 50, 50));

        btn9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 50, 50));

        btnDot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDot.setText(".");
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });
        getContentPane().add(btnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 50, 50));

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setText("C");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 50, 50));

        btn0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, 50));

        btnPlus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 50, 50));

        btnSub.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSub.setText("-");
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });
        getContentPane().add(btnSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 50, 50));

        btnMul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMul.setText("*");
        btnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulActionPerformed(evt);
            }
        });
        getContentPane().add(btnMul, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 50, 50));

        btnDiv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDiv.setText("/");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 50, 50));

        btnEql.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEql.setText("=");
        btnEql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqlActionPerformed(evt);
            }
        });
        getContentPane().add(btnEql, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 50, 50));

        bksc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bksc.setText("bk");
        bksc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkscActionPerformed(evt);
            }
        });
        getContentPane().add(bksc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, 50));

        ans.setText("jLabel1");
        getContentPane().add(ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        store.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeActionPerformed(evt);
            }
        });
        getContentPane().add(store, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 160, -1));

        in.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        in.setText("-+");
        in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inActionPerformed(evt);
            }
        });
        getContentPane().add(in, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 50, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        String take = Display.getText() + btn9.getText();
       Display.setText(take);
       String st = store.getText() + btn9.getText();
       store.setText(st);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       Display.setText("");
       Result = 0;
       res = 1;
       First = 0;
       min = 0;
       store.setText("");
       ans.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulActionPerformed
        // TODO add your handling code here:
        String take = Display.getText() + btnMul.getText();
        Display.setText(take);
        
        operator= "*";
        Get();
        ans.setText(""+Result);
    }//GEN-LAST:event_btnMulActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        // TODO add your handling code here:
        String take = Display.getText() + btnDiv.getText();
        Display.setText(take);
        
        operator= "/";
        Get();
        ans.setText(""+Result);
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnEqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqlActionPerformed
        Get();
        Display.setText(""+Result);
       // else JOptionPane.showMessageDialog(null, "hmmm");
        
    }//GEN-LAST:event_btnEqlActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
       String take = Display.getText() + btn1.getText();
       Display.setText(take);
       String st = store.getText() + btn1.getText();
       store.setText(st);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        String take = Display.getText() + btn2.getText();
       Display.setText(take);
       String st = store.getText() + btn2.getText();
       store.setText(st);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        String take = Display.getText() + btn3.getText();
       Display.setText(take);
       String st = store.getText() + btn3.getText();
       store.setText(st);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        String take = Display.getText() + btn4.getText();
       Display.setText(take);
       String st = store.getText() + btn4.getText();
       store.setText(st);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        String take = Display.getText() + btn5.getText();
       Display.setText(take);
       String st = store.getText() + btn5.getText();
       store.setText(st);
       
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        String take = Display.getText() + btn6.getText();
       Display.setText(take);
       String st = store.getText() + btn6.getText();
       store.setText(st);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        String take = Display.getText() + btn7.getText();
       Display.setText(take);
       String st = store.getText() + btn7.getText();
       store.setText(st);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        String take = Display.getText() + btn8.getText();
       Display.setText(take);
       String st = store.getText() + btn8.getText();
       store.setText(st);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        String take = Display.getText() + btnDot.getText();
       Display.setText(take);
       String st = store.getText() + btnDot.getText();
       store.setText(st);
    }//GEN-LAST:event_btnDotActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
       String take = Display.getText() + btn0.getText();
       Display.setText(take);
       String st = store.getText() + btn0.getText();
       store.setText(st);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        String take = Display.getText() + btnPlus.getText();
        Display.setText(take);
        
        operator= "+";
        Get();
        ans.setText(""+Result);
        
        
        
       
    }//GEN-LAST:event_btnPlusActionPerformed

    private void DisplayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DisplayKeyReleased
        
                
    }//GEN-LAST:event_DisplayKeyReleased

    private void storeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storeActionPerformed

    private void inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inActionPerformed
       double temp =Double.parseDouble(Display.getText()) ;
       temp = temp * (-1);
       Display.setText(""+temp);
    }//GEN-LAST:event_inActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayActionPerformed

    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubActionPerformed
       String take = Display.getText() + btnSub.getText();
        Display.setText(take);
       
        operator= "-";
        Get();
        ans.setText(""+Result);
    }//GEN-LAST:event_btnSubActionPerformed

    private void bkscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkscActionPerformed
        backSp();

    }//GEN-LAST:event_bkscActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Display;
    private javax.swing.JLabel ans;
    private javax.swing.JButton bksc;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnEql;
    private javax.swing.JButton btnMul;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnSub;
    private javax.swing.JButton in;
    private javax.swing.JTextField store;
    // End of variables declaration//GEN-END:variables
}
