/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rizwan
 */
public class IslamicDateConverter extends javax.swing.JFrame {

    /**
     * Creates new form IslamicDateConverter
     */
    public IslamicDateConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yyyy = new javax.swing.JTextField();
        mm = new javax.swing.JTextField();
        dd = new javax.swing.JTextField();
        umm = new javax.swing.JLabel();
        uyyyy = new javax.swing.JLabel();
        udd = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        get = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("URDU DATE CONVERTER");
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        yyyy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yyyy.setBorder(null);
        yyyy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yyyyActionPerformed(evt);
            }
        });
        getContentPane().add(yyyy, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 74, 68, 20));

        mm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mm.setBorder(null);
        mm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmActionPerformed(evt);
            }
        });
        getContentPane().add(mm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 74, 30, 20));

        dd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dd.setBorder(null);
        dd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddActionPerformed(evt);
            }
        });
        getContentPane().add(dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 74, 30, 20));
        dd.getAccessibleContext().setAccessibleDescription("");

        umm.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        umm.setForeground(new java.awt.Color(0, 153, 0));
        umm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        umm.setText("mm");
        umm.setToolTipText("");
        getContentPane().add(umm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 177, 30));

        uyyyy.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        uyyyy.setForeground(new java.awt.Color(0, 153, 0));
        uyyyy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uyyyy.setText("yyyy");
        getContentPane().add(uyyyy, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 60, 30));

        udd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        udd.setForeground(new java.awt.Color(0, 153, 0));
        udd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        udd.setText("dd");
        getContentPane().add(udd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 60, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 240));

        get.setText("get");
        get.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        get.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getActionPerformed(evt);
            }
        });
        getContentPane().add(get, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yyyyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yyyyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yyyyActionPerformed

    private void getActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getActionPerformed

       int  d = Integer.parseInt(dd.getText());
       int  m = Integer.parseInt(mm.getText());
       int  y =  Integer.parseInt(yyyy.getText());
       
       int i,UMon=0;
		float tempy,x=365;
		int week[] = {31,28,31,30,31,30,31,31,30,31,30,31};
		int temp = 0;
		for(i=0; i<m-1; i++)
		{
			temp = temp + week[i];
		}
		int TotalDays = temp + d;
		if(y%4==0 && m>2 || y%4==0 && m==2 && d==29 )
		{
		TotalDays++;
		x++;
		}
		tempy = (TotalDays/x);
		double Totalyears = y + tempy;
		double Hijri = (Totalyears - 621.54)/0.970255 ;
		double TotalUdays = (Hijri - (int)Hijri)*354;
		while(TotalUdays>29)
		{
			TotalUdays = TotalUdays - 29.5;
			UMon++;
		}
		TotalUdays = TotalUdays + 4;
                String MONTHS[] = {"MOHAARAM", "SAFAR", "RABI-AAWAL", "RABI-SANI", "JAMADI-AWWAL", "JAMADI-SANI", "RAJAB", "SHABAN", "RAMZAN", "EID", "KHAALI", "HAJJ"};
                
                udd.setText("" + (int)TotalUdays);
                umm.setText("" + MONTHS[UMon]);
                uyyyy.setText("" + (int)Hijri);
        // TODO add your handling code here:
    }//GEN-LAST:event_getActionPerformed

    private void mmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mmActionPerformed

    private void ddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IslamicDateConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IslamicDateConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IslamicDateConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IslamicDateConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IslamicDateConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dd;
    private javax.swing.JButton get;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField mm;
    private javax.swing.JLabel udd;
    private javax.swing.JLabel umm;
    private javax.swing.JLabel uyyyy;
    private javax.swing.JTextField yyyy;
    // End of variables declaration//GEN-END:variables
}
