/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EnquiryGUI;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author rizwan
 */
public class AddmisionCell extends javax.swing.JFrame {

    /**
     * Creates new form AddmisionCell
     */
    int count = 0;
    public AddmisionCell() {
        initComponents();
        enquiry.setVisible(false);
        drop.setVisible(false);
        Guest.setText("+ Logged as Guest");
        getDate();
    }
    
        Thread t;
    Runnable r = new Runnable() {
        @Override
        public void run() {
            try{
                while(true)
                {
                    Date date = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("E dd-MM-yyyy | KK:mm:ss a");
        time.setText(ft.format(date)+"");
                }
                
            }catch(Exception e){}
        
            }
    };
    public void getDate() 
    {
      t = new Thread(r);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JPanel();
        school = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        web = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        msg2 = new javax.swing.JLabel();
        pic_head = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        pic2_head = new javax.swing.JLabel();
        headlogo = new javax.swing.JLabel();
        pic_bar = new javax.swing.JLabel();
        bar = new javax.swing.JLabel();
        Main_home = new javax.swing.JScrollPane();
        home_main = new javax.swing.JPanel();
        Guest = new javax.swing.JLabel();
        drop = new javax.swing.JPanel();
        update = new javax.swing.JLabel();
        changepaswd = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        logout = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        dp = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Registration = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        Noti = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        intro = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        mqp = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        fs = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        inq = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        enquiry = new javax.swing.JScrollPane();
        main = new javax.swing.JPanel();
        side = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ptab = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tab = new javax.swing.JLabel();
        feebg = new javax.swing.JLabel();
        sidebg = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        addbg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        Enquiiry = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        reg = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADDMISSION CELL");
        setBackground(new java.awt.Color(255, 255, 255));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head.setBackground(new java.awt.Color(0, 0, 0));
        head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        school.setFont(new java.awt.Font("Baskerville Old Face", 1, 60)); // NOI18N
        school.setForeground(new java.awt.Color(102, 0, 0));
        school.setText("Zeal educates");
        head.add(school, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        phone.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\phone.png")); // NOI18N
        phone.setText("   +91 8755 235450");
        head.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        web.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\web.png")); // NOI18N
        web.setText("   www.Zealeducates.com");
        head.add(web, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        title.setFont(new java.awt.Font("Brush Script MT", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(102, 0, 0));
        title.setText("Education that changes life...");
        head.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, 30));

        msg2.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\msg2.png")); // NOI18N
        head.add(msg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 70));

        pic_head.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\pic_head.png")); // NOI18N
        head.add(pic_head, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        msg.setText("<html>  <font size = 4 face = Lucida Sans color = #aa3b3b > <b> <i>\" Education is provider of alernative view of the worlds and a strengthener of the will to explore them\" <i> </b> </font> </html>");
        head.add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 720, -1));

        pic2_head.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\pic2_head.png")); // NOI18N
        head.add(pic2_head, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, -1, -1));

        headlogo.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\head.png")); // NOI18N
        head.add(headlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 150));

        pic_bar.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\pic_bar.png")); // NOI18N
        head.add(pic_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 150, -1, -1));

        bar.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\bar.png")); // NOI18N
        head.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 190));

        home_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Guest.setBackground(new java.awt.Color(255, 255, 255));
        Guest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Guest.setForeground(new java.awt.Color(51, 102, 255));
        Guest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Guest.setText("Logged as Guest");
        Guest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Guest.setOpaque(true);
        Guest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GuestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GuestMouseExited(evt);
            }
        });
        home_main.add(Guest, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 140, 20));

        drop.setBackground(new java.awt.Color(204, 204, 255));
        drop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        update.setBackground(new java.awt.Color(0, 204, 255));
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        update.setText("☼ Update Profile");
        update.setOpaque(true);
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        drop.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 124, 140, 27));

        changepaswd.setBackground(new java.awt.Color(0, 204, 255));
        changepaswd.setForeground(new java.awt.Color(255, 255, 255));
        changepaswd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changepaswd.setText("Change Password");
        changepaswd.setOpaque(true);
        changepaswd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changepaswdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changepaswdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changepaswdMouseExited(evt);
            }
        });
        drop.add(changepaswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 153, 140, 27));
        drop.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 140, -1));

        logout.setBackground(new java.awt.Color(0, 204, 255));
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("Logout");
        logout.setOpaque(true);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        drop.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 182, 140, 27));
        drop.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 122, 140, -1));

        dp.setBackground(new java.awt.Color(255, 255, 255));
        dp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dp.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\dp.jpg")); // NOI18N
        dp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dp.setOpaque(true);
        drop.add(dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 121));
        drop.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 151, 140, -1));

        home_main.add(drop, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 140, 210));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Welcome To Addmission Cell");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, 850, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Session 2016 - 2017");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 840, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\mainpic.png")); // NOI18N
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 260, 400));

        jLabel21.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\admfo.png")); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        home_main.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 860, 470));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Home.setForeground(new java.awt.Color(51, 102, 255));
        Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Home.setText("Home");
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.setOpaque(true);
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });
        jPanel2.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 29));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, -1));

        Registration.setBackground(new java.awt.Color(255, 255, 255));
        Registration.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Registration.setForeground(new java.awt.Color(51, 102, 255));
        Registration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Registration.setText("Registration Formalities");
        Registration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Registration.setOpaque(true);
        Registration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistrationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistrationMouseExited(evt);
            }
        });
        jPanel2.add(Registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 210, 28));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 210, -1));

        Noti.setBackground(new java.awt.Color(255, 255, 255));
        Noti.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Noti.setForeground(new java.awt.Color(51, 102, 255));
        Noti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Noti.setText("Notifications");
        Noti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Noti.setOpaque(true);
        Noti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NotiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NotiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NotiMouseExited(evt);
            }
        });
        jPanel2.add(Noti, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 210, 28));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, -1));

        intro.setBackground(new java.awt.Color(255, 255, 255));
        intro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        intro.setForeground(new java.awt.Color(51, 102, 255));
        intro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        intro.setText("Introduction");
        intro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        intro.setOpaque(true);
        intro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                introMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                introMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                introMouseExited(evt);
            }
        });
        jPanel2.add(intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 92, 210, 28));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, -1));

        mqp.setBackground(new java.awt.Color(255, 255, 255));
        mqp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mqp.setForeground(new java.awt.Color(51, 102, 255));
        mqp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mqp.setText("Model Question Paper");
        mqp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mqp.setOpaque(true);
        mqp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mqpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mqpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mqpMouseExited(evt);
            }
        });
        jPanel2.add(mqp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 122, 210, 28));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, -1));

        fs.setBackground(new java.awt.Color(255, 255, 255));
        fs.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fs.setForeground(new java.awt.Color(51, 102, 255));
        fs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fs.setText("Fee Structure");
        fs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fs.setOpaque(true);
        fs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fsMouseExited(evt);
            }
        });
        jPanel2.add(fs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 152, 210, 28));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 210, -1));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 102, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Syllabus");
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.setOpaque(true);
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel28MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel28MouseExited(evt);
            }
        });
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 182, 210, 28));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 210, -1));

        inq.setBackground(new java.awt.Color(255, 255, 255));
        inq.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        inq.setForeground(new java.awt.Color(51, 102, 255));
        inq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inq.setText("Inquiry Broucher");
        inq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inq.setOpaque(true);
        inq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inqMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inqMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inqMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inqMousePressed(evt);
            }
        });
        jPanel2.add(inq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 212, 210, 28));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 210, -1));

        home_main.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 210, 250));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\logo.png")); // NOI18N
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        time.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        time.setForeground(new java.awt.Color(255, 0, 51));
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setText("Logged as Hussain");
        jPanel3.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, -1));

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Help Line : 9720360817");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 40, 190, -1));

        home_main.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 210, 200));

        Main_home.setViewportView(home_main);

        getContentPane().add(Main_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1366, -1));

        enquiry.setBackground(new java.awt.Color(153, 255, 255));

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side.setBackground(new java.awt.Color(255, 255, 255));
        side.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        side.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Principal Desk");
        side.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 217, -1, -1));

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fee Details");
        side.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        ptab.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\bodyEnq\\ptab.png")); // NOI18N
        side.add(ptab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 214, -1, -1));

        pic.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\bodyEnq\\pp.png")); // NOI18N
        side.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 31, -1, 220));

        jLabel20.setText("<html> <pre> “We understand the value of<br>  time in business, and we<br>  value yours. Whether your<br>  needs are proactive or you <br> have an unexpected issue,<br>  we are available to assist  you”.  </pre>  </html>");
        side.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 250, 170));

        tab.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\bodyEnq\\tab.png")); // NOI18N
        side.add(tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, -1));

        feebg.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\bodyEnq\\feebg.png")); // NOI18N
        side.add(feebg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        sidebg.setText("<html> <body bgcolor=white width =260 height=700>  </htm");
        side.add(sidebg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, 610));

        main.add(side, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Eligibility for obtaining Application Form");
        body.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel17.setText("<html> <ul> <li>    Parents should be qualified upto 12th Standard. <li>     Parents will interface a interview,  they must be pass in it. <li>  \t\t  Average 75% in last result  <li>  \t\t  Average 75% and above in English, Science and Mathematics in ICSE \t\t\t     Board Examinations <li>  \t\t  Average 80% and above in English, Science and Mathematics in CBSE \t\t\t    and other Board Examinations \t\t\t\t<ul> </html>");
        body.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel16.setText("<html>We take addmission on the basis of  Entrance Test ,  if student are fulfill  our criteria, we will obtain a  test form Rs. 120/- <p> <b> Toal Seat : 80 <b>  </html>");
        body.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel19.setText("<html> <ul> <li>\t\tCampus <li> \t\tLab <li> \t\tHostel <li> \t\tTransport <li> \t\tSmart Classess <li> \t\tScience park <li>\t\tLibarary <li> \t\tSports <li> \t\tSeminar Room <li>\t\tGymnasium <li>\t\tWiFi <li>\t\tSports & Ground </ul> </html> ");
        body.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 260, -1, -1));

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Rules & Regulation");
        body.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        jLabel13.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Addmission Procedure");
        body.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Facilities");
        body.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, -1, -1));

        jLabel18.setText("<html> <ul> <li>Discipline is necessary for the smooth and efficient running of the school. Punctuality, Neatness, Courtesy,  Generosity, Hard work, <br> Consideration for others, Cooperation spirit is insisted upon in the school.  <li>Discipline is also necessary to help the students to acquire self-discipline, without which a person cannot  become upright and <br> grow towards freedom. True freedom is the ability to freely choose what is really  true and good. But, <br> “it is a long way to freedom”.   <li>A student’s mistakes are tolerated to some extent as part of the process of growing up, but repeated  misbehavior <br> and action against the spirit of the school is not tolerated even if this causes <br> pain to the  parents of the stubborn, uncooperative student. </ul> </html>");
        body.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 465, -1, -1));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel3.setText("Address");
        body.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 158, -1, -1));

        address.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        address.setText("<html>  Contact us today: +91 875523545 <p> <p> zeal educates <br> Modinagar, Uttar Pradesh 201204, India<br> Freephone: +91.8755235450 <br> Telephone:  +91.8755235450<br> FAX:  +91.8755235450<br> E-mail: zealeducates@gmail.com<br> </html>");
        body.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 22, 260, 140));

        addbg.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\bodyEnq\\add.png")); // NOI18N
        addbg.setOpaque(true);
        body.add(addbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\bodyEnq\\proc_tab.png")); // NOI18N
        body.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\bodyEnq\\procbg.png")); // NOI18N
        body.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\bodyEnq\\eligitab.png")); // NOI18N
        body.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\bodyEnq\\eligbg.jpg")); // NOI18N
        body.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\bodyEnq\\rulestab.png")); // NOI18N
        body.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\bodyEnq\\rulesbg.png")); // NOI18N
        body.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\bodyEnq\\faciltab.png")); // NOI18N
        body.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\Zeal\\GUI\\bodyEnq\\facbg.png")); // NOI18N
        body.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, -1, -1));

        main.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1070, -1));

        enquiry.setViewportView(main);

        getContentPane().add(enquiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1366, 450));

        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jMenuBar1.add(home);

        jMenu1.setText("Addmision");

        Enquiiry.setText("Enquiry");
        Enquiiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnquiiryActionPerformed(evt);
            }
        });
        jMenu1.add(Enquiiry);
        jMenu1.add(jSeparator1);

        reg.setText("Registration");
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        jMenu1.add(reg);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Fee Detail");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenu2MouseEntered(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
     
    }//GEN-LAST:event_homeActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
         this.setTitle("ADDMISSION CELL");
        enquiry.setVisible(false);
        Main_home.setVisible(true);
    }//GEN-LAST:event_homeMouseClicked

    private void jMenu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseEntered

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
      
    }//GEN-LAST:event_jMenu2MouseClicked
    int c = 0;
    private void GuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuestMouseClicked
     
        c++;
     
        if(c%2!=0)
        { 
           Guest.setText("X Logged as Guest");
           drop.setVisible(true);
        }
        else
        {
          Guest.setText("+ Logged as Guest");  
          drop.setVisible(false);  
        }
    
     
       
    }//GEN-LAST:event_GuestMouseClicked

    private void GuestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuestMouseEntered
       // Guest.setForeground(Color.darkGray);
       
    }//GEN-LAST:event_GuestMouseEntered

    private void GuestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuestMouseExited
      // Guest.setForeground(null);
      
    }//GEN-LAST:event_GuestMouseExited

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        JOptionPane.showMessageDialog(null, "under working");

    }//GEN-LAST:event_regActionPerformed

    private void EnquiiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnquiiryActionPerformed
        this.setTitle("ADDMISSION CELL - Enquiry");
        Main_home.setVisible(false);
        enquiry.setVisible(true);
    }//GEN-LAST:event_EnquiiryActionPerformed

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
       update.setBackground(new Color(0,102,255));
       update.setForeground(Color.YELLOW);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        update.setBackground(new Color(0,204,255));
       update.setForeground(Color.white);
    }//GEN-LAST:event_updateMouseExited

    private void changepaswdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepaswdMouseEntered
        changepaswd.setBackground(new Color(0,102,255));
       changepaswd.setForeground(Color.YELLOW);
    }//GEN-LAST:event_changepaswdMouseEntered

    private void changepaswdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepaswdMouseExited
        changepaswd.setBackground(new Color(0,204,255));
       changepaswd.setForeground(Color.white);
    }//GEN-LAST:event_changepaswdMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
         logout.setBackground(new Color(0,102,255));
       logout.setForeground(Color.YELLOW);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
         logout.setBackground(new Color(0,204,255));
       logout.setForeground(Color.white);
    }//GEN-LAST:event_logoutMouseExited

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
          
       update.setBackground(Color.red);
       update.setForeground(Color.white);
       JOptionPane.showMessageDialog(null, "update profile");
    }//GEN-LAST:event_updateMouseClicked

    private void changepaswdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepaswdMouseClicked
         changepaswd.setBackground(Color.red);
       changepaswd.setForeground(Color.white);
    }//GEN-LAST:event_changepaswdMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
          logout.setBackground(Color.red);
       logout.setForeground(Color.white);
    }//GEN-LAST:event_logoutMouseClicked

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        Home.setForeground(Color.white);
        Home.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        Home.setForeground(new Color(51,102,255));
        Home.setBackground(Color.white);
    }//GEN-LAST:event_HomeMouseExited

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        Home.setBackground(Color.red);
        Home.setForeground(Color.white);
    }//GEN-LAST:event_HomeMouseClicked

    private void RegistrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrationMouseEntered
        Registration.setForeground(Color.white);
        Registration.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_RegistrationMouseEntered

    private void RegistrationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrationMouseExited
        Registration.setForeground(new Color(51,102,255));
        Registration.setBackground(Color.white);
    }//GEN-LAST:event_RegistrationMouseExited

    private void RegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrationMouseClicked
       Registration.setBackground(Color.red);
       Registration.setForeground(Color.white);
    }//GEN-LAST:event_RegistrationMouseClicked

    private void NotiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotiMouseEntered
        Noti.setForeground(Color.white);
        Noti.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_NotiMouseEntered

    private void NotiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotiMouseExited
        Noti.setForeground(new Color(51,102,255));
        Noti.setBackground(Color.white);
    }//GEN-LAST:event_NotiMouseExited

    private void NotiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotiMouseClicked
        Noti.setBackground(Color.red);
       Noti.setForeground(Color.white);
    }//GEN-LAST:event_NotiMouseClicked

    private void introMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_introMouseEntered
         intro.setForeground(Color.white);
        intro.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_introMouseEntered

    private void introMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_introMouseExited
            intro.setForeground(new Color(51,102,255));
        intro.setBackground(Color.white);
    }//GEN-LAST:event_introMouseExited

    private void introMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_introMouseClicked
        intro.setBackground(Color.red);
      intro.setForeground(Color.white);
    }//GEN-LAST:event_introMouseClicked

    private void mqpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mqpMouseEntered
        mqp.setForeground(Color.white);
        mqp.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_mqpMouseEntered

    private void mqpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mqpMouseExited
         mqp.setForeground(new Color(51,102,255));
        mqp.setBackground(Color.white);
    }//GEN-LAST:event_mqpMouseExited

    private void mqpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mqpMouseClicked
          mqp.setBackground(Color.red);
      
    }//GEN-LAST:event_mqpMouseClicked

    private void fsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fsMouseEntered
          fs.setBackground(new Color(0,204,255));
          fs.setForeground(Color.white);
    }//GEN-LAST:event_fsMouseEntered

    private void fsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fsMouseExited
          fs.setForeground(new Color(51,102,255));
         fs.setBackground(Color.white);
    }//GEN-LAST:event_fsMouseExited

    private void fsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fsMouseClicked
        fs.setBackground(Color.red);
    }//GEN-LAST:event_fsMouseClicked

    private void jLabel28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseEntered
        jLabel28.setBackground(new Color(0,204,255));
          jLabel28.setForeground(Color.white);
    }//GEN-LAST:event_jLabel28MouseEntered

    private void jLabel28MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseExited
        jLabel28.setForeground(new Color(51,102,255));
         jLabel28.setBackground(Color.white);
    }//GEN-LAST:event_jLabel28MouseExited

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        jLabel28.setBackground(Color.red);
    }//GEN-LAST:event_jLabel28MouseClicked

    private void inqMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inqMouseEntered
        inq.setBackground(new Color(0,204,255));
          inq.setForeground(Color.white);
    }//GEN-LAST:event_inqMouseEntered

    private void inqMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inqMouseExited
        inq.setForeground(new Color(51,102,255));
         inq.setBackground(Color.white);
    }//GEN-LAST:event_inqMouseExited

    private void inqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inqMouseClicked
        inq.setBackground(Color.red);
        this.setTitle("ADDMISSION CELL - Enquiry");
        Main_home.setVisible(false);
        enquiry.setVisible(true);
    }//GEN-LAST:event_inqMouseClicked

    private void inqMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inqMousePressed
        inq.setBackground(Color.red);
    }//GEN-LAST:event_inqMousePressed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        
    }//GEN-LAST:event_formKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddmisionCell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddmisionCell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddmisionCell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddmisionCell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddmisionCell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Enquiiry;
    private javax.swing.JLabel Guest;
    private javax.swing.JLabel Home;
    private javax.swing.JScrollPane Main_home;
    private javax.swing.JLabel Noti;
    private javax.swing.JLabel Registration;
    private javax.swing.JLabel addbg;
    private javax.swing.JLabel address;
    private javax.swing.JLabel bar;
    private javax.swing.JPanel body;
    private javax.swing.JLabel changepaswd;
    private javax.swing.JLabel dp;
    private javax.swing.JPanel drop;
    private javax.swing.JScrollPane enquiry;
    private javax.swing.JLabel feebg;
    private javax.swing.JLabel fs;
    private javax.swing.JPanel head;
    private javax.swing.JLabel headlogo;
    private javax.swing.JMenu home;
    private javax.swing.JPanel home_main;
    private javax.swing.JLabel inq;
    private javax.swing.JLabel intro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel main;
    private javax.swing.JLabel mqp;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel msg2;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel pic2_head;
    private javax.swing.JLabel pic_bar;
    private javax.swing.JLabel pic_head;
    private javax.swing.JLabel ptab;
    private javax.swing.JMenuItem reg;
    private javax.swing.JLabel school;
    private javax.swing.JPanel side;
    private javax.swing.JLabel sidebg;
    private javax.swing.JLabel tab;
    private javax.swing.JLabel time;
    private javax.swing.JLabel title;
    private javax.swing.JLabel update;
    private javax.swing.JLabel web;
    // End of variables declaration//GEN-END:variables
}
