/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package School;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author rizwan
 */
public class TeacherProfile extends javax.swing.JFrame {

    /**
     * Creates new form TeacherProfile
     */
    public TeacherProfile() {
        initComponents();
        profile.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profile = new javax.swing.JPanel();
        photo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        basicInfo = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        Contact = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        quali = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        capability = new javax.swing.JLabel();
        steach = new javax.swing.JLabel();
        joining = new javax.swing.JLabel();
        lab1 = new javax.swing.JLabel();
        lab2 = new javax.swing.JLabel();
        lab3 = new javax.swing.JLabel();
        uid = new javax.swing.JPanel();
        signatue = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        id_lab = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        getID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profile Info", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Agency FB", 1, 18), java.awt.Color.red)); // NOI18N
        profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        photo.setToolTipText("profile photo");

        jLabel3.setText("photo");

        javax.swing.GroupLayout photoLayout = new javax.swing.GroupLayout(photo);
        photo.setLayout(photoLayout);
        photoLayout.setHorizontalGroup(
            photoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(photoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel3)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        photoLayout.setVerticalGroup(
            photoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(photoLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel3)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        profile.add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 145, -1));

        basicInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        Contact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        label5.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 18)); // NOI18N
        label5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label5.setText("Qualification :");

        label1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label1.setText("Name                :");

        label2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label2.setText("Contact            :");

        label3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label3.setText("Address            :");

        label4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label4.setText("Email ID            :");

        quali.setFont(new java.awt.Font("Bell Gothic Std Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout basicInfoLayout = new javax.swing.GroupLayout(basicInfo);
        basicInfo.setLayout(basicInfoLayout);
        basicInfoLayout.setHorizontalGroup(
            basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5)
                    .addGroup(basicInfoLayout.createSequentialGroup()
                        .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55)
                        .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quali, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 108, Short.MAX_VALUE))
        );
        basicInfoLayout.setVerticalGroup(
            basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Contact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 35, Short.MAX_VALUE)
                .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(basicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        profile.add(basicInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 530, 200));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        capability.setFont(new java.awt.Font("BrowalliaUPC", 0, 24)); // NOI18N
        capability.setText("N/A");
        jLayeredPane1.add(capability, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 30));

        steach.setFont(new java.awt.Font("BrowalliaUPC", 0, 24)); // NOI18N
        jLayeredPane1.add(steach, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 46, 210, 30));

        joining.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        jLayeredPane1.add(joining, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        lab1.setFont(new java.awt.Font("BrowalliaUPC", 0, 24)); // NOI18N
        lab1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab1.setText("Teaching Capability :");
        jLayeredPane1.add(lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, 150, -1));

        lab2.setFont(new java.awt.Font("BrowalliaUPC", 0, 24)); // NOI18N
        lab2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab2.setText("Subject Teacher     :");
        jLayeredPane1.add(lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 46, 150, -1));

        lab3.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        lab3.setText("Date Of Joining :");
        jLayeredPane1.add(lab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        profile.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 690, 140));

        uid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        uid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signatue.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        signatue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signatue.setText("Signature");
        signatue.setAlignmentY(5.0F);
        uid.add(signatue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 30));

        profile.add(uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 145, 50));

        close.setBackground(new java.awt.Color(255, 0, 0));
        close.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        close.setForeground(new java.awt.Color(102, 102, 102));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("X");
        close.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(51, 0, 0), new java.awt.Color(153, 0, 0)));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        close.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                closeFocusGained(evt);
            }
        });
        profile.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 20, -1));

        id_lab.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        id_lab.setForeground(new java.awt.Color(51, 153, 0));
        id_lab.setText("ID No :");
        profile.add(id_lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, -1));

        id.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        id.setForeground(new java.awt.Color(51, 153, 0));
        id.setText("xxxxxxxx");
        profile.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 170, -1));

        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, 710, 430));

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Techear's  Detail");

        jButton1.setText("Find");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel2.setText("Teacher's ID :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(getID, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(getID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 710, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try {
         
      int uid = Integer.parseInt(getID.getText());
      if(uid == 1001)
      {   
          new TeacherList();
          id.setText( "" + TeacherList.ID);
          name.setText( TeacherList.Name);
          email.setText( TeacherList.Email);
          Contact.setText("" + TeacherList.Contact);
          quali.setText( TeacherList.Quali);
          steach.setText(TeacherList.Sub_Teacher);
          joining.setText(TeacherList.Join_Date);
          profile.setVisible(true); 
      }
      else if(uid==0000)
      {
          profile.setVisible(true);
      }
      else JOptionPane.showMessageDialog(null, "not found");
     }catch(Exception e)
     {
         
     }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void closeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_closeFocusGained
        
    }//GEN-LAST:event_closeFocusGained

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        profile.setVisible(false);
        name.setText("");
        email.setText( "");
        Contact.setText("" );
        quali.setText("");
        steach.setText("");
          joining.setText("");
          id.setText( "xxxxxxxx");
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
       close.setForeground(Color.RED);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setForeground(null);
    }//GEN-LAST:event_closeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contact;
    private javax.swing.JLabel address;
    private javax.swing.JPanel basicInfo;
    private javax.swing.JLabel capability;
    private javax.swing.JLabel close;
    private javax.swing.JLabel email;
    private javax.swing.JTextField getID;
    private javax.swing.JLabel id;
    private javax.swing.JLabel id_lab;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel joining;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel name;
    private javax.swing.JPanel photo;
    private javax.swing.JPanel profile;
    private javax.swing.JLabel quali;
    private javax.swing.JLabel signatue;
    private javax.swing.JLabel steach;
    private javax.swing.JPanel uid;
    // End of variables declaration//GEN-END:variables
}
