/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roommanagment;

import java.awt.Color;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author rizwan
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public static String name;
    public static String userid;
    public static String getmode;
    static String getPass;
    public static Connection conn;
    
    //int bounds = (Toolkit.getDefaultToolkit().getScreenSize().width) - 500;
    public Login()  {
        this.setUndecorated(true);
        //this.setLocation(bounds, 150);
        initComponents();
        mobile.setVisible(false);
        hintmob.setVisible(false);
        getConnection();
    }

    public static void getConnection() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/roommanagement", "root", "");
            System.out.println("connected");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void getLogin() {
        String u = user.getText();
        String p = pass.getText();
        String md = (String) mode.getSelectedItem();
        if (md.equals("--Select Mode--")) {
            //System.out.println("please select mode");
            JOptionPane.showMessageDialog(null, "please select mode");
        } else if (u.length() == 0 || p.length() == 0) {
            //System.out.println("fields are empty");
            JOptionPane.showMessageDialog(null, "fields are empty");
        } else {

            boolean flag = false;
            try {
                PreparedStatement pst = conn.prepareStatement("SELECT * FROM membersrecord ");
                ResultSet rs = pst.executeQuery();

                while (rs.next()) {
                    if (u.equals(rs.getString(1)) && p.equals(rs.getString(2)) && md.equalsIgnoreCase(rs.getString(8))) {
                        flag = true;
                        userid = rs.getString(1);
                        getPass = rs.getString(2);
                        getmode = rs.getString(8);
                        name = rs.getString(3).toUpperCase();
                    }

                }
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (flag) {
                new Main().setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Username or password is Incorrect");
            }

        }
    }

    private String getPassword(String usermob) {
        boolean flag = false;
        String pass = null;
        try {
            PreparedStatement pst = conn.prepareStatement("SELECT * FROM membersrecord ");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                if (usermob.equals(rs.getString(10))) {
                    flag = true;
                    pass = rs.getString(2);
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        if (usermob.equals("9720360817")) {
            return "You can't find devloper password";
        } else if (flag) {
            return "Your password is " + pass;
        } else {
            return usermob + " is not in record";
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        hintpass = new javax.swing.JLabel();
        hintuser = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        mode = new javax.swing.JComboBox<>();
        hintmob = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        forgot = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hintpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hintpass.setForeground(new java.awt.Color(204, 255, 204));
        hintpass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hintpass.setText("Enter Password");
        hintpass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(hintpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, 20));

        hintuser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hintuser.setForeground(new java.awt.Color(204, 255, 204));
        hintuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hintuser.setText("Enter Username");
        hintuser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(hintuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 127, 150, 20));

        user.setBackground(new java.awt.Color(233, 167, 74));
        user.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        user.setForeground(new java.awt.Color(255, 51, 51));
        user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        user.setBorder(null);
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userFocusLost(evt);
            }
        });
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 122, 161, 30));

        pass.setBackground(new java.awt.Color(233, 167, 74));
        pass.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 51, 51));
        pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass.setBorder(null);
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFocusLost(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 166, 161, 30));

        mode.setBackground(new java.awt.Color(102, 255, 102));
        mode.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mode.setForeground(new java.awt.Color(0, 153, 102));
        mode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Mode--", "Admin", "Member" }));
        mode.setOpaque(false);
        jPanel1.add(mode, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 160, -1));

        hintmob.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        hintmob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hintmob.setText("Enter Registered Mobile");
        hintmob.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(hintmob, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 140, -1));

        mobile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mobile.setOpaque(false);
        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });
        mobile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mobileFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mobileFocusLost(evt);
            }
        });
        jPanel1.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 256, 140, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\rizwan\\Desktop\\RM\\exit.png")); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rizwan\\Desktop\\RM\\raw\\login.png")); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        forgot.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        forgot.setText("Forgot Passowrd ?");
        forgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgotMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                forgotMousePressed(evt);
            }
        });
        jPanel1.add(forgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\rizwan\\Desktop\\RM\\bg.jpg")); // NOI18N
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundMousePressed(evt);
            }
        });
        background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundMouseDragged(evt);
            }
        });
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 301));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        getLogin();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked

    }//GEN-LAST:event_userMouseClicked

    private void userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusGained
        hintuser.setVisible(false);

    }//GEN-LAST:event_userFocusGained

    private void userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusLost
        if (user.getText().length() == 0) {
            hintuser.setVisible(true);
        }

    }//GEN-LAST:event_userFocusLost

    private void passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusGained
        hintpass.setVisible(false);
    }//GEN-LAST:event_passFocusGained

    private void passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusLost
        if (pass.getText().length() == 0) {
            hintpass.setVisible(true);
        }
    }//GEN-LAST:event_passFocusLost

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        mobile.setVisible(false);
        hintmob.setVisible(false);
        String pass = getPassword(mobile.getText());
        JOptionPane.showMessageDialog(null, pass);
        mobile.setText("");
    }//GEN-LAST:event_mobileActionPerformed

    int count = 0;

    private void forgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMouseClicked
        count++;
        if (count % 2 != 0) {
            mobile.setVisible(true);
            mobile.setOpaque(false);
            mobile.setBackground(new Color(0, 0, 0, 0));
            hintmob.setVisible(true);
        } else {
            mobile.setVisible(false);
            hintmob.setVisible(false);
        }

    }//GEN-LAST:event_forgotMouseClicked

    private void mobileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobileFocusGained
        hintmob.setVisible(false);
    }//GEN-LAST:event_mobileFocusGained

    private void mobileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobileFocusLost
        if (mobile.getText().length() == 0) {
            hintmob.setVisible(false);
        }
    }//GEN-LAST:event_mobileFocusLost

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
         getLogin();
    }//GEN-LAST:event_passActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        getLogin();
    }//GEN-LAST:event_userActionPerformed

    private void forgotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMouseEntered
       forgot.setText("<html> <u> Forgot Passowrd ? </u> </html>");
    }//GEN-LAST:event_forgotMouseEntered

    private void forgotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMouseExited
        forgot.setText("Forgot Passowrd ?");
    }//GEN-LAST:event_forgotMouseExited

    private void forgotMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMousePressed
        
    }//GEN-LAST:event_forgotMousePressed
    int xMouse;
    int yMouse;
    private void backgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_backgroundMousePressed

    private void backgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_backgroundMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel forgot;
    private javax.swing.JLabel hintmob;
    private javax.swing.JLabel hintpass;
    private javax.swing.JLabel hintuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField mobile;
    private javax.swing.JComboBox<String> mode;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
